feat: создание архитектуры
G-Grechits/java-explore-with-me pull request #1
Opened 2022-11-16 16:18 UTC by G-Grechits

2022-11-27 19:01 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/EwmService.java
> +public class EwmService {
Обожаю этот класс! 
В нём никто не делает ошибок... ))

Привет, Георгий!

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/client/BaseClient.java
> +        return makeAndSendRequest(HttpMethod.GET, path, parameters, null);
Применяя предварительный импорт статиков получим более читабельный и удобный код... 

`return makeAndSendRequest(GET, path, parameters, null);`

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/controller/privateController/PrivateEventController.java
> +package ru.practicum.controller.privateController;
Не корректное, с точки зрения `Java naming convention` название пакета.
Можно применять только нижний регистр. Есть есть желание разделить два слова то применяем `_`

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/dto/CompilationDto.java
> +    private String title;
Нет ни одной аннотации по валидации... допустима модель без `id` и с пустым `title` ?

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/dto/EventFullDto.java
> +public class EventFullDto {
Смотри две модели `EventFullDto` and `EventShortDto` имеют одни и те же свойства, можно ведь не дублировать их в каждой модели, а вынести общую часть в некий `EventBaseDto`...

Ну и опять же не вилидируем ни одного поля, работу только начал смотреть, пока не пойму почему у тебя так...

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/dto/NewCompilationDto.java
> +    @NotBlank
О, вот тут начали встречаться аннотации, тут всё верно.

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/dto/NewEventDto.java
> +    private Integer participantLimit;
@PositiveOrZero ??

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/dto/UserShortDto.java
> +    private String name;
В `UserDto` `name` был @NotBlank  а тут?

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/entity/Compilation.java
> +    @Column(nullable = false)
Делай отступы между полями.... когда присутствует ворох аннотаций всё сливается!

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +        log.error("Возникла ошибка 400: {}", e.getMessage());
Логируй ошибки вместе со стек-трейсом

`log.error("Возникла ошибка 400: {}", e.getMessage(), e);`

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +        log.error("Возникла ошибка 403: {}", e.getMessage());
403 код связан с правами и доступом. Этого нет в нашей работе, 
Поэтому стоит найти более подходящий ексепшн к тем ситуациям когда ты используешь ForbiddenException и заменить его.

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/repository/EventRepository.java
> +    findAllByAnnotationContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndCategoryIdInAndPaidAndEventDateBetween(
Надо иметь железную силу воли чтобы это собрать! ))

Но я бы попросил тебя написать Query вместо того чтобы ставить рекорды на самое длинное название метода ))

2022-11-27 19:01 UTC, FanaticFiz commented on stats-server/src/main/resources/application.properties
> +server.port=9090
Я "топлю" за то чтобы студенты сразу привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`

Соответственно - попрошу тебя этому следовать.

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS requests
Отлично!
Тут всё сделано как надо.

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryService.java
> +    CategoryDto createCategory(CategoryDto categoryDto);
Давай на этом примере поговорим про название методов.

Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `сategoryService.createCategory()`

Получается масло-масляное! 

Лучше: `сategoryService.create()` `сategoryService.update / delete`

Более того! Такие названия помогут тебе увидеть что многие сервисы, да и не только они, пересекаются по функционалу и могут быть унифицированы!
Стремись к этому!

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryServiceImpl.java
> +        checkName(categoryDto.getName());
В этом методы ты кидаешь ексепшн. Будет честно назвать метод соответствующе: `throwIfNameExist`

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryServiceImpl.java
> +        return CategoryMapper.toCategoryDto(categoryRepository.save(category));
`categoryRepository.save(category)` 
Именно это действие является тут главным - не прячь его, оно достойно отдельной строки кода.

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryServiceImpl.java
> +        Category formerCategory = getCategoryFromRepository(categoryDto.getId());
`getCategoryFromRepository` почему-то многим нравится так делать, но я считаю это не уместным. Мы ничего не выиграли в плане упрощения кода.
Но получили метод в который надо ходить и смотреть что же там происходит.

```
    @Override
    public CategoryDto updateCategory(CategoryDto categoryDto) {
        Category formerCategory = getCategoryFromRepository(categoryDto.getId());
        checkName(categoryDto.getName());
        formerCategory.setName(categoryDto.getName());
        return CategoryMapper.toCategoryDto(categoryRepository.save(formerCategory));
    }
```

Вот моя версия, с отступами, чуть больше получилось конечно

```
    @Override
    public CategoryDto updateCategory(CategoryDto categoryDto) {
        checkName(categoryDto.getName());
        
        Category formerCategory = categoryRepository
                .findById(categoryDto.getId())
                .orElseThrow(() -> new NotFoundException("Не найдена категория с id: " + categoryDto.getId()));

        formerCategory.setName(categoryDto.getName());
        Category saved = categoryRepository.save(formerCategory);
        
        return CategoryMapper.toCategoryDto(saved);
    }
```

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminUserServiceImpl.java
> +        return userRepository.findAll(pageable).stream()
Есть хорошая практика делать отступ перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminUserServiceImpl.java
> +    public List<UserDto> getUsersByIds(List<Long> ids) {
```
    @Override
    public List<UserDto> getUsersByIds(List<Long> ids) {
        return userRepository.findAllById(ids).stream()
                             .map(UserMapper::toUserDto)
                             .collect(Collectors.toList());
    }
```

2022-11-27 19:01 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminUserServiceImpl.java
> +    public UserDto createUser(UserDto userDto) {
Теперь исходя из всех предыдущих комментов, просто пример: 

```
    @Override
    public UserDto createUser(UserDto userDto) {
        userRepository.findByEmail(userDto.getEmail())
                      .ifPresent(user -> {
                          throw new ConflictException(
                                  "уже зарегистрирован пользователь с электронной почтой: " + user.getEmail());
                      });

        User saved = userRepository.save(toUser(userDto));

        return toUserDto(saved);
    }
```

2022-11-27 19:01 UTC, FanaticFiz commented on stats-server/src/main/java/ru/practicum/HitRepository.java
> +    @Query("select count(ip) from Hit where uri = ?1")
Пиши SQL команды в верхнем регистре: `select` -> `SELECT`

2022-11-27 19:35 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/EwmService.java
> +public class EwmService {
Мне тоже нравится)

2022-11-27 19:38 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/dto/EventFullDto.java
> +public class EventFullDto {
Отвечу сразу касательно всех подобных DTO: я не ставил валидационные аннотации в тех классах, объекты которых мы только отправляем, а не принимаем. Зачем они там, если всё равно нигде нет какой-нибудь @Valid, которая проверит их поля на соответствия требованиям?

2022-11-27 19:47 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +        log.error("Возникла ошибка 403: {}", e.getMessage());
Объясни, пожалуйста, подробнее, что именно мне стоит изменить, не до конца понятно.

2022-11-27 19:51 UTC, G-Grechits commented on stats-server/src/main/resources/application.properties
> +server.port=9090
Нам ничего об этом не рассказывали ни наставники, ни в теоретической части. Достаточно просто создать документ в этом формате и перенести туда всё, что указано в properties?

2022-11-27 19:53 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryService.java
> +    CategoryDto createCategory(CategoryDto categoryDto);
А я нарочно так называл для единообразия...окей, исправлю.

2022-11-27 19:57 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryServiceImpl.java
> +        Category formerCategory = getCategoryFromRepository(categoryDto.getId());
Вынужден не согласиться. Предыдущий ревьюер, который был со мной с самого начала, учил меня не писать дублирующийся код. Считаю, что лучше написать отдельный приватный метод, чем в 4 методах прописать один тот же блок.

2022-11-27 20:00 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryServiceImpl.java
> +        return CategoryMapper.toCategoryDto(categoryRepository.save(category));
Написать отдельной строкой или исправить вышестоящую на **_Category category = **categoryRepository.save(CategoryMapper.toCategory(categoryDto));_** ?

2022-11-27 20:17 UTC, G-Grechits commented on stats-server/src/main/java/ru/practicum/HitRepository.java
> +    @Query("select count(ip) from Hit where uri = ?1")
Только команды? По поводу count, from, where тоже скажи, пожалуйста - чтобы уж ещё одну итерацию на это не тратить потом.

2022-11-27 20:18 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminUserServiceImpl.java
> +        return userRepository.findAll(pageable).stream()
Как понимаю, во всех методах нужно отделить, не только в этом?)

2022-11-28 07:00 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/dto/EventFullDto.java
> +public class EventFullDto {
Отлично, это я и хотел услышать! ))

2022-11-28 07:05 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryServiceImpl.java
> +        Category formerCategory = getCategoryFromRepository(categoryDto.getId());
Я принимаю твою точку зрения. 
Тут очень тонкая грань. У тебя же самого по проекту в остальных местах получение из репозитория и последующий orElseThrow в отдельные методы не выносится.

Тут будет зависеть от того как принято делать в том или ином проекте и команде.

2022-11-28 07:07 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminUserServiceImpl.java
> +        return userRepository.findAll(pageable).stream()
В целом да, конечно же! 
Но я понимаю что это может быть затратно и тут при обучении мы можем это проигнорировать.
Главное что это было подсвечено тебе, как мне кажется...

2022-11-28 07:08 UTC, FanaticFiz commented on stats-server/src/main/java/ru/practicum/HitRepository.java
> +    @Query("select count(ip) from Hit where uri = ?1")
Да да, я имел ввиду все служебные слова из синтаксиса SQL

2022-11-28 14:41 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +        log.error("Возникла ошибка 403: {}", e.getMessage());
Денис, привет, вот здесь всё же можешь подробнее объяснить, что от меня требуется?

2022-11-28 14:44 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +        log.error("Возникла ошибка 403: {}", e.getMessage());
Заменить ForbiddenException на какой то из более подходящих по смыслу.
По ситуации надо посмотреть может это BadRequestException - 400 код
Может быть ConflictException - 409 код?
Может быть NotFoundException - 404 код, если не найдено что-то...

2022-11-28 14:47 UTC, G-Grechits commented on stats-server/src/main/resources/application.properties
> +server.port=9090
И вот тут ещё вопрос задавал...

2022-11-28 14:48 UTC, FanaticFiz commented on stats-server/src/main/resources/application.properties
> +server.port=9090
Да я знаю что вам это не дают...
Но я даю это своим студентам, чтобы вы были максимально приближены к современным реалиям.

Если решишься переделать, то надо самостоятельно поискать инфу...
Переименовать у файла расширение недостаточно. Свойства будут записываться немного по другому.

2022-11-28 14:49 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryService.java
> +    CategoryDto createCategory(CategoryDto categoryDto);
Консистентность это хорошо, но лучше бы в другую сторону!
В смысле в сторону упрощения названий ))

2022-11-28 14:50 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/adminService/AdminCategoryServiceImpl.java
> +        return CategoryMapper.toCategoryDto(categoryRepository.save(category));
Да будет валидно... особенно если не забыть сократить за счет импорта статического метода мапера...

`Category category = categoryRepository.save(toCategory(categoryDto));`

2022-11-28 14:53 UTC, FanaticFiz commented on stats-server/src/main/resources/application.properties
> +server.port=9090
Вот так оно выглядит
```
server:
  port: 8084

spring:
  profiles: fiz-dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5434/crg_data_service
    username: fiz
    password: 314
```

2022-11-29 21:00 UTC, G-Grechits commented on stats-server/src/main/resources/application.properties
> +server.port=9090
Денис, привет! Я исправил код, учитывая все твои рекомендации (не считая тех моментов, в которых мы пришли к консенсусу), кроме одного места: application.yml. Я немного почитал на эту тему, но изменять не решился - пока далеко не всё понятно, поэтому боюсь напортачить, к тому же работа, обновлённые тесты и последующая разработка фичи с созданием тестов для неё добавляют стресса... Но я обещаю в будущем изучить эту тему, обязательно! Большое спасибо за уделённое время и ценные советы)

2022-11-30 03:58 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-30 03:58 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Не досмотрел в первый раз.
Тут же у тебя дублирование кода, когда ты разные ексепшены к ответу `@ResponseStatus(HttpStatus.BAD_REQUEST)` приводишь.

А ведь есть возможность для одного обработчика указать несколько классов:
`@ExceptionHandler({NotFoundException.class, ValidationException.class})`

2022-11-30 03:58 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/EventStatsService.java
> +    public Integer getViews(long id) {
Вот еще важный момент!
С самим этим методом всё норм...
Но то как его используют в некоторых случаях не норм!

Я имею ввиду использование этого метода в цикле
![image](https://user-images.githubusercontent.com/3994663/204703116-c51b288d-a7fe-4b39-a87f-2fec4e4cd701.png)

На скрине это три раза, там где `.map`

`HitController` специально же сделан так что принимает `List<String> uris`
А мы этим не пользуемся! Дёргая по одному, что естественно бьёт по производительности и деградирует с ростом `events`.


Что нужно делать?
После того как получили `events`, не перебирать их в цикле и ходить за каждым по отдельности, а выбрать всё одним запросом!

2022-11-30 03:58 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/service/private_service/PrivateRequestService.java
> +    List<ParticipationRequestDto> get(long userId);
Я конечно же настаивать уже не буду, но просто подсвечу еще раз.
После того как названия методов упростились, ты должен был заметить сходство между интерфейсами и в будущем старайся писать их более универсальными через `T`

2022-11-30 11:12 UTC, G-Grechits commented on ewm-service/src/main/java/ru/practicum/service/private_service/PrivateRequestService.java
> +    List<ParticipationRequestDto> get(long userId);
Обязательно!

2022-12-01 04:05 UTC, FanaticFiz approved these changes

2022-12-01 04:05 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +    @ExceptionHandler({BadRequestException.class, ValidationException.class})
Ну ты даёшь!
Я же кинул тебе эти два ексепшена просто для примера, как их объединять!
У тебя то в работе объединить надо было больше и MissingServletRequestParameterException и MethodArgumentNotValidException
Всё что отдаётся как BAD_REQUEST и имеет под собой одинаковый код обработки!

2022-12-01 13:09 UTC, merged